### ISSUE TITLE
KeyError in 'Fantasy_Stats.py'

### ISSUE THREAD

**Issue by chanalytics-ai** [yahoo-fantasy/nfl-fantasy-football#12]
Oops - another KeyError. This time KeyError: 'game'. Trying to trace back to see where the issue could be but could use your help on this one @bbenbenek !

> Traceback (most recent call last):
>   File "/Users/williamchan/PycharmProjects/cll/fantasy_stats.py", line 307, in <module>
>     main()
>   File "/Users/williamchan/PycharmProjects/cll/fantasy_stats.py", line 275, in main
>     bot.run()
>   File "/Users/williamchan/PycharmProjects/cll/fantasy_stats.py", line 286, in run
>     UD.UpdateYahooLeagueInfo()
>   File "/Users/williamchan/PycharmProjects/cll/fantasy_stats.py", line 207, in UpdateYahooLeagueInfo
>     game_key = r['fantasy_content']['game'][0]['game_key'] # game key as type-string
> KeyError: 'game'

**Comment by bbenbenek** [comment]
What does the response variable 'r' look like when you are running that? What code is it giving you, 200, 400, 500? My gut tells me it's a bad response from the API meaning it's either a wrong game_key/league _id combination that's giving you a "Not authorized to view because you are not in this league". This could also happen if you didn't authorize your app correctly or a simple API glitch.

It's looking for 'game' within the response json, but it doesn't exist because it's trying to tell you something else is wrong.

**Comment by chanalytics-ai** [comment]
Script works fine for the current season actually. I was trying to code it for historical but I couldn't get it to work...
